### ISSUE TITLE
setting property to self

### ISSUE THREAD

**Issue by bendichter** [ben-dichter-consulting/lazy_ops#11]
This is an unusual thing to do:

https://github.com/ben-dichter-consulting/lazy_ops/blob/38432436dfa3eced8d6a2a73062f303bb05e154e/lazy_ops/lazy_loading.py#L38

Is there a reason for this? Why can't you just use `self` instead of `self._lazy_slice`?

**Comment by d-sot** [comment]
This was a leftover from a much earlier iteration. It should be fixed in 0ad986a364ace52ffa8ecd888106dea0ec581dbf
