### ISSUE TITLE
stand-alone transpose function

### ISSUE THREAD

**Issue by bendichter** [ben-dichter-consulting/lazy_ops#15]
It would be nice to have the function `lazy_transpose(Dataset, axes=None)` similar to [numpy's](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html)

**Comment by bendichter** [comment]
```python
def lazy_transpose(dset):
    return dset.lazy_transepose()
```

**Comment by d-sot** [comment]
This is added in 3557198e52ffcb0b9961be4b1e0f9cd4801d96c8 .
