### ISSUE TITLE
methods should be underscore_case

### ISSUE THREAD

**Issue by bendichter** [ben-dichter-consulting/lazy_ops#5]
I think I may have caused some confusion when changing things. According to PEP8, class names should be CamelCase ([source](https://www.python.org/dev/peps/pep-0008/#class-names)) and instances and methods should be underscore_case ([source](https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables)), so the syntax should be: 

```python
dsetview.lazy_slice[1:10:2,:,0:50:5].lazy_transpose([2,0,1]).lazy_slice[25:55,1,1:4:1,:]
```

**Comment by d-sot** [comment]
The methods use the correct naming convention now.
