### ISSUE TITLE
instance attributes defined outside init

### ISSUE THREAD

**Issue by bendichter** [ben-dichter-consulting/lazy_ops#8]
It is best practice to have all attributes defined within `__init__`. `self.reversed_axis_order` (line 128) and `self.key_reinit` (line 186) are attributes defined outside `__init__`. This is ok if there is a good reason for doing it this way, but it would be better to not define attributes outside `__init__` if we can avoid it. We could either remove the `self` and make these local variables or initialize them to `None` in `__init__`.

**Comment by d-sot** [comment]
They're local variables now in 38432436dfa3eced8d6a2a73062f303bb05e154e . I had considered using as class attributes but it became necessary.
